source 'https://rubygems.org'
ruby '2.2.2'

gem 'rails'
gem 'sass-rails'
gem 'haml-rails'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'uglifier'
gem 'pg'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks', :git => 'https://github.com/rails/turbolinks.git'
gem 'jbuilder'
gem 'sdoc', group: :doc
gem 'bcrypt'
gem 'thin'
group :development, :test do
  gem 'byebug'
  gem 'bullet'
  gem 'web-console'
  gem 'spring'
  gem 'pry'
  gem 'pry-nav'
  gem 'rspec-rails'
end
